---
- name: Clone the code repository to the app directory.
  git:
    repo: "{{ git_repo }}"
    dest: "{{ application_path }}"
    version: "{{ branch }}"
    accept_hostkey: yes
    force: yes
    key_file: "{{ user_home_folder }}/.ssh/id_rsa"
    ssh_opts: "-o StrictHostKeyChecking=no"
  register: git

- name: prepare environment file
  template:
    src: env.j2
    dest: "{{ application_path }}/.env"

- name: Install package
  command: "yarn install"
  args:
    chdir: "{{ application_path }}/"

- name: Build source
  command: "{{ item }}"
  with_items:
    - yarn build
  args:
    chdir: "{{ application_path }}/"

- name: Copy process file to run by pm2
  template:
    src: "process.yaml.j2"
    dest: "{{ application_path }}/process.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0600

- name: Run source
  command: "pm2 start process.yaml"
  args:
    chdir: "{{ application_path }}/"

# - name: save pm2
#   command: "pm2 save"
#   args:
#     chdir: "{{ application_path }}/"

- name: Reload nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
  become: yes

- name: Check port nginx is running
  wait_for:
    port: "80"
    state: started
    delay: 3   
