export const businessUnitSearchConstants = {
  GET_LARGE_UNITS_FOR_SEARCH: 'GET_LARGE_UNITS_FOR_SEARCH',
  GET_MEDIUM_UNITS_FOR_SEARCH: 'GET_MEDIUM_UNITS_FOR_SEARCH',
  GET_SMALL_UNITS_FOR_SEARCH: 'GET_SMALL_UNITS_FOR_SEARCH',
  SAVE_BUSINESS_SEARCH_PARAMS: 'SAVE_BUSINESS_SEARCH_PARAMS',
  GET_ALL_BUSINESS_FOR_SEARCH: 'GET_ALL_BUSINESS_FOR_SEARCH',
};
