export const departmentConstants = {
  GET_DEPARTMENTS: 'GET_DEPARTMENTS',
  SEARCH_DEPARTMENTS: 'SEARCH_DEPARTMENTS',
  GET_DEPARTMENTS_FOR_BUSINESS_UNIT: 'GET_DEPARTMENTS_FOR_BUSINESS_UNIT',
  CREATE_DEPARTMENT: 'CREATE_DEPARTMENT',
  GET_DEPARTMENT_DETAIL: 'GET_DEPARTMENT_DETAIL',
  DELETE_DEPARTMENT: 'DELETE_DEPARTMENT',
  UPDATE_DEPARTMENT: 'UPDATE_DEPARTMENT',
  BULK_UPDATE_DEPARTMENTS: 'BULK_UPDATE_DEPARTMENTS',
  BULK_INSERT_DEPARTMENTS: 'BULK_INSERT_DEPARTMENTS',
  GET_DEPARTMENTS_FOR_EDIT_USER: 'GET_DGET_DEPARTMENTS_FOR_EDIT_USERPARTMENTS',
  CLEAR_DEPARTMENTS: 'CLEAR_DEPARTMENTS',
};
