export const organizationConstants = {
  GET_ORGANIZATIONS: 'GET_ORGANIZATIONS',
  CREATE_ORGANIZATION: 'CREATE_ORGANIZATION',
  GET_ORGANIZATION: 'GET_ORGANIZATION',
  UPDATE_ORGANIZATION: 'UPDATE_ORGANIZATION',
  DELETE_ORGANIZATION: 'DELETE_ORGANIZATION',
};
