export const regulationTypeConstants = {
  GET_REGULATION_TYPES: 'GET_REGULATION_TYPES',
  CREATE_REGULATION_TYPES: 'CREATE_REGULATION_TYPES',
  DELETE_REGULATION_TYPES: 'DELETE_REGULATION_TYPES',
};
