export const regulationConstants = {
  GET_REGULATIONS: 'GET_REGULATIONS',
  CREATE_REGULATION: 'CREATE_REGULATION',
  GET_REGULATION: 'GET_REGULATION',
  DELETE_REGULATIONS: 'DELETE_REGULATIONS',
  UPDATE_REGULATION: 'UPDATE_REGULATION',
  BULK_INSERT_REGULATIONS: 'BULK_INSERT_REGULATIONS',
};
