export const usersConstant = {
  GET_USERS: 'GET_USERS',
  CREATE_USER: 'CREATE_USER',
  GET_USER_DETAIL: 'GET_USER_DETAIL',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  RESEND_PASSWORD: 'RESEND_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
};
